version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PIPENV_ARGS: --dev
    command:
    - flask
    - run
    - --host=0.0.0.0
    ports:
    - ${PORT:-5000}:5000
    environment:
     FLASK_DEBUG: '1'
     FLASK_APP: app
    volumes:
    - ./:/usr/src/app
